version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "api-gw-serverless-app"
s3_bucket = "aws-sam-cli-managed-default-582140066777"
s3_prefix = "sam/prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Env=prod"
no_fail_on_empty_changeset = true
disable_rollback = true
