# .github/workflows/deploy-to-eks.yml
name: Reusable Deploy to EKS Cluster

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      role_to_assume:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-eks:
    name: 'Deploy Applications to EKS Cluster'
    runs-on: ubuntu-latest
    outputs:
      LB_DNS: ${{ steps.get-dns-name.outputs.LB_DNS }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::582140066777:role/github-action-role
          aws-region: ${{ inputs.aws_region }}
      
      - name: get caller identity 
        run: aws sts get-caller-identity
        
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      - name: Get Kubernetes cluster info
        run: kubectl cluster-info

      - name: Deploy Kubernetes Manifests
        working-directory: ./.github/workflows/../.././infrastructure/
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: get LB DNS name
        id: get-dns-name
        run:
       # Capture Load Balancer DNS into LB_DNS variable
          LB_DNS=$(kubectl get svc nginx-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')         
          echo "LB_DNS=$LB_DNS" >> $GITHUB_ENV

