# .github/workflows/deploy-to-eks.yml
name: Reusable Deploy to EKS Cluster

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      role_to_assume:
        required: true
        type: string
env:
  ECR_REGISTRY: 582140066777.dkr.ecr.us-east-1.amazonaws.com  # Update with your ECR registry
  ECR_REPO: nginx  # Update with your ECR repository
  



permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-eks:
    name: 'Deploy Applications to EKS Cluster'
    runs-on: ubuntu-latest
    outputs:
      lb_dns: ${{ steps.get_dns_name.outputs.lb_dns }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::582140066777:role/github-action-role
          aws-region: ${{ inputs.aws_region }}
      
      - name: get caller identity 
        run: aws sts get-caller-identity
        
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      - name: Get Kubernetes cluster info
        run: kubectl cluster-info

      # Install Metrics Server for HPA requirements
      - name: Install Metrics Server
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

      # Verify Metrics Server Installation
      - name: Verify Metrics Server
        run: |
          kubectl get deployment metrics-server -n kube-system
          
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        working-directory: ./.github/workflows/../.././infrastructure/k8s/
        run: |
          # Define the image name and tag
          
          IMAGE_TAG=$(git rev-parse --short HEAD)
          # Build the Docker image
          docker build -t ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG} .

          # Push the Docker image to ECR
          docker push ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}

      - name: Initiate ECR Image Scan
        run: |
         aws ecr start-image-scan --repository-name ${ECR_REGISTRY}/${ECR_REPO}  --image-id imageTag=${IMAGE_TAG}

      - name: Deploy Kubernetes Manifests deployment hpa service 
        working-directory: ./.github/workflows/../.././infrastructure/
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/hpa.yaml
          kubectl apply -f k8s/service.yaml

      - name: Deploy NGINX
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          kubectl set image deployment/nginx-deployment nginx=$ECR_REGISTRY/$ECR_REPO:${IMAGE_TAG}
          kubectl rollout status deployment/nginx-deployment
      
      - name: get LB DNS name
        id: get_dns_name
        run: |
          lb_dns=$(kubectl get svc nginx-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')         
          echo $lb_dns
          echo "lb_dns=$lb_dns" >> output.txt
          cat output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-output
          path: output.txt

