# .github/workflows/control-deploy.yml
name: Control Deploy Workflow

on:
  push:
    branches:
      - github-action-api-gw-lambda-dynamodb
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  provision-eks:
    name: 'Provision EKS Cluster'
    uses: ./.github/workflows/provision-eks.yml
    with:
      aws_region: us-east-1
      role_to_assume: arn:aws:iam::582140066777:role/github-action-role  # Update with your role ARN
  
  deploy-to-eks:
    name: 'Deploy Applications to EKS'
    needs: [provision-eks]
    uses: ./.github/workflows/deploy-to-eks.yml
    with:
      aws_region: us-east-1
      role_to_assume: arn:aws:iam::582140066777:role/github-action-role  # Update with your role ARN
    
  echo-dns-name: 
     runs-on: ubuntu-latest
     name: 'echo alb dns name'
     needs: [deploy-to-eks]
     steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-output
      - name: Read the output
        run: |
          cat output.txt
  
  build-deploy-serverless:
    name: 'Build and Deploy Serverless Components'
    needs: [echo-dns-name]
    uses: ./.github/workflows/build-deploy-serverless.yml
    with:
      aws_region: us-east-1
      role_to_assume: arn:aws:iam::582140066777:role/github-action-role  # Update with your role ARN
      



  integration-tests:
    name: 'Run Integration Tests'
    needs: [build-deploy-serverless]
    uses: ./.github/workflows/integration-tests.yml
    with:
      api_endpoint: ${{ needs.build-deploy-serverless.outputs.api_endpoint }}
      api_key: ${{ needs.build-deploy-serverless.outputs.api_key }}
